title: "The Family Video Archive"
email: your-email@example.com
description: "A curated collection of videos for the whole family to enjoy." # <--- FIXED THIS LINE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: your-github-username # Not strictly necessary, but good practice

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock